name: Long running tests

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  NUM_FUNCTIONAL_TEST_ITERATIONS: 20000

# Ensures that we cancel running jobs for the same PR / same workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:

    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install stable
      uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
      with:
          toolchain: stable
          profile: minimal
          override: true

    - name: Run indexing_unsorted
      run: cargo test indexing_unsorted -- --ignored
    - name: Run indexing_sorted
      run: cargo test indexing_sorted -- --ignored
